spring:
  application:
    name: template
  profiles:
    active: 'local'

#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST:localhost}
#    port: 5672
#    username: rabbitmq
#    password: rabbitmq

#  datasource:
#    url: ${SPRING_DATASOURCE_URL_VAR:jdbc:postgresql://localhost:5432/template}
#    username: user
#    password: password
#    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:/db/changelog.xml
#    user: user
#    password: password
#    enabled: true
#  jpa:
#    open-in-view: false
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true

#  data:
#    redis:
#      host: ${SPRING_REDIS_HOST:localhost}
#      port: 6379
#      password: password
#      timeout: 6000
